# Generated by Django 3.0 on 2021-10-24 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Dialog'), ('C', 'Chat')], default='D', max_length=1, verbose_name='')),
            ],
            options={
                'db_table': 'Chat',
            },
        ),
        migrations.CreateModel(
            name='Chat_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_message', models.TextField(verbose_name='')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='')),
                ('is_readed', models.BooleanField(default=False, verbose_name='')),
                ('chat_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatSystem.Chat', verbose_name='chat')),
            ],
            options={
                'db_table': 'Chat message',
                'ordering': ['pub_date'],
            },
        ),
    ]
