# Generated by Django 3.0 on 2021-11-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='photoUser',
            field=models.ImageField(default='media/image/user/index.jpg', upload_to='image/userImage/%Y/%m/', verbose_name='photo'),
        ),
    ]
