# Generated by Django 3.0 on 2021-11-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211124_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='photoUser',
            field=models.ImageField(default='image/user/index.jpg', upload_to='image/userImage/%Y/%m/', verbose_name='photo'),
        ),
    ]
