# Generated by Django 3.0 on 2022-06-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0003_auto_20211126_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='slugCustomUser',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='uniqueNameCustomUsers',
        ),
        migrations.AlterField(
            model_name='customusers',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
