# Generated by Django 3.0 on 2021-10-24 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='AuthorComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='authorArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='dislikeArticle',
            field=models.ManyToManyField(blank=True, related_name='dislikeArticle', to='analytics.IpUser'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='likeArticle',
            field=models.ManyToManyField(blank=True, related_name='likeArticle', to='analytics.IpUser'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tagsArticle',
            field=models.ManyToManyField(to='article.TagsModel', verbose_name="Tag's"),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='viewArticle',
            field=models.ManyToManyField(blank=True, related_name='viewArticle', to='analytics.IpUser'),
        ),
    ]
