# Generated by Django 3.0 on 2021-11-26 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20211024_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='dislikeArticle',
            field=models.ManyToManyField(blank=True, related_name='dislikeArticle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='likeArticle',
            field=models.ManyToManyField(blank=True, related_name='likeArticle', to=settings.AUTH_USER_MODEL),
        ),
    ]
