# Generated by Django 3.0 on 2022-06-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_likedislikemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='dislikeArticle',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='likeArticle',
        ),
        migrations.DeleteModel(
            name='LikeDislikeModel',
        ),
    ]
